/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3afa8f44-d77c-48d9-89ea-a624db9cb2f4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_5TCBNDweq",
    "aws_user_pools_web_client_id": "2073vktkkq23p9qtot1d3gc6kv",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://d7s3pr5y3vegtlmntdehhmnmi4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
